name: Manual Trigger

on:
  workflow_dispatch

jobs:
  test_manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "This is a manually triggered workflow."